version: "3"

services:
  rpc-twitter:
    tty: true
    image: rpc-twitter:1.0
    restart: unless-stopped
    ports:
    - '50081:50081'
    command: [ "make", "run-twitter"]

  rpc-instagram:
    tty: true
    image: rpc-instagram:1.0
    restart: unless-stopped
    environment:
      - REDIS_HOST=localhost
    ports:
      - '50082:50082'
    command: [ "make", "run-instagram" ]

  api-rpc-twitter:
    image: rpc-twitter:1.0
    restart: always
    environment:
      - SANIC_NO_UVLOOP=true
      - SANIC_NO_UJSON=true
      - RPC_HOST=172.17.0.1
    ports:
    - '50181:50181'
    command: ["make", "run-rest_twitter"]