# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import twitter_pb2 as proto_dot_twitter__pb2


class twitterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRequest = channel.unary_unary(
                '/twitter.twitter/StreamRequest',
                request_serializer=proto_dot_twitter__pb2.twitterRequest.SerializeToString,
                response_deserializer=proto_dot_twitter__pb2.twitterResponse.FromString,
                )


class twitterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def StreamRequest(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_twitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamRequest,
                    request_deserializer=proto_dot_twitter__pb2.twitterRequest.FromString,
                    response_serializer=proto_dot_twitter__pb2.twitterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twitter.twitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class twitter(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def StreamRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twitter.twitter/StreamRequest',
            proto_dot_twitter__pb2.twitterRequest.SerializeToString,
            proto_dot_twitter__pb2.twitterResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
